/** Kanonische BestPay-Produkte laut belegten Unterlagen (interne Produktcodes). */
export const BESTPAY_PRODUCTS_RAW = [
  {
    id: 'product_bestpay_premium_line_register',
    name: 'BestPay Premium Line Kassensystem',
    providerName: 'BestPay',
    internalProductCode: 'BP-CASH-PREMIUM-LINE',
    category: 'cash_register',
    status: 'active',
    description:
      'Finanzamtkonforme Android-Registrierkasse mit integriertem SEIKO-Belegdrucker, Aluminiumgehäuse, Service und Kartenterminal.',
    manufacturer: null,
    modelName: 'Premium Line',
    supportedTerminalTypes: ['stationary'],
    priceType: 'monthly',
    priceCents: 11995,
    secondaryPriceType: 'one_time',
    secondaryPriceCents: 24995,
    secondaryPriceLabel: 'Swissbit TSE Stick',
    unitLabel: 'je Kassensystem',
    includedFeatures: [
      'Kassensoftware Premium inklusive',
      'Zahlsystemintegration inklusive',
      'Service inklusive',
      'Kartenterminal inklusive',
    ],
    technicalFeatures: [
      'Android-Registrierkasse',
      'Integrierter SEIKO-Belegdrucker',
      'Aluminiumlegierung',
      'TSE-konform',
      'GoBD-konform',
      'KassenSichV-konform',
      'Software made in Germany',
    ],
    sourceReference: 'Standardangebot PremiumLine.pdf',
    notes:
      'Vertragslaufzeit laut Angebot monatlich kündbar. Optionaler Einrichtungspreis wird als separates Dienstleistungsprodukt geführt.',
    validFrom: null,
    validUntil: '2026-07-31',
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_bestpay_premium_line_setup',
    name: 'Einrichtung Premium Line',
    providerName: 'BestPay',
    internalProductCode: 'BP-SERVICE-PREMIUM-SETUP',
    category: 'service',
    status: 'active',
    description: 'Optionale einmalige Einrichtung für das BestPay Premium Line Kassensystem.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['stationary'],
    priceType: 'one_time',
    priceCents: 39995,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Einrichtung',
    includedFeatures: [],
    technicalFeatures: [],
    sourceReference: 'Standardangebot PremiumLine.pdf',
    notes: 'Im Angebot ausdrücklich als optional gekennzeichnet.',
    validFrom: null,
    validUntil: '2026-07-31',
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_printer',
    name: 'Speedypay Drucker',
    providerName: 'BestPay',
    internalProductCode: 'BP-MODULE-PRINTER',
    category: 'cash_register_module',
    status: 'active',
    description: 'Zusätzlicher Drucker für Speedypay-Kassensysteme.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['stationary'],
    priceType: 'monthly',
    priceCents: 1295,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Drucker',
    includedFeatures: [],
    technicalFeatures: ['Epson oder Sam4s'],
    sourceReference: 'Zusatzmodule.pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_signature_server',
    name: 'Speedypay Signaturserver',
    providerName: 'BestPay',
    internalProductCode: 'BP-MODULE-SIGNATURE-SERVER',
    category: 'cash_register_module',
    status: 'active',
    description: 'Signaturserver für Speedypay-Kassensysteme.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['stationary'],
    priceType: 'monthly',
    priceCents: 995,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Signaturserver',
    includedFeatures: [],
    technicalFeatures: [],
    sourceReference: 'Zusatzmodule.pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_tse_sd',
    name: 'Speedypay TSE-SD-Karte',
    providerName: 'BestPay',
    internalProductCode: 'BP-MODULE-TSE-SD',
    category: 'cash_register_module',
    status: 'active',
    description: 'TSE-SD-Karte für Speedypay-Kassensysteme.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['stationary', 'mobile'],
    priceType: 'monthly',
    priceCents: 995,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je TSE-SD-Karte',
    includedFeatures: [],
    technicalFeatures: ['TSE'],
    sourceReference: 'Zusatzmodule.pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_tse_usb',
    name: 'Speedypay TSE-USB-Stick',
    providerName: 'BestPay',
    internalProductCode: 'BP-MODULE-TSE-USB',
    category: 'cash_register_module',
    status: 'active',
    description: 'TSE-USB-Stick für Speedypay-Kassensysteme.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['stationary', 'mobile'],
    priceType: 'monthly',
    priceCents: 995,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je TSE-USB-Stick',
    includedFeatures: [],
    technicalFeatures: ['TSE'],
    sourceReference: 'Zusatzmodule.pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_cash_drawer_small',
    name: 'Speedypay Kassenschublade klein',
    providerName: 'BestPay',
    internalProductCode: 'BP-MODULE-CASH-DRAWER-S',
    category: 'cash_register_module',
    status: 'active',
    description: 'Kleine Kassenschublade für Speedypay-Kassensysteme.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['stationary'],
    priceType: 'monthly',
    priceCents: 595,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Kassenschublade',
    includedFeatures: [],
    technicalFeatures: ['Ausführung klein'],
    sourceReference: 'Zusatzmodule.pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_cash_drawer_large',
    name: 'Speedypay Kassenschublade groß',
    providerName: 'BestPay',
    internalProductCode: 'BP-MODULE-CASH-DRAWER-L',
    category: 'cash_register_module',
    status: 'active',
    description: 'Große Kassenschublade für Speedypay-Kassensysteme.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['stationary'],
    priceType: 'monthly',
    priceCents: 795,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Kassenschublade',
    includedFeatures: [],
    technicalFeatures: ['Ausführung groß'],
    sourceReference: 'Zusatzmodule.pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_ccv_a960',
    name: 'CCV A960 inklusive Software',
    providerName: 'BestPay',
    internalProductCode: 'BP-CASH-CCV-A960',
    category: 'cash_register',
    status: 'active',
    description: 'Mobiles Kassensystem CCV A960 inklusive Software.',
    manufacturer: 'CCV',
    modelName: 'A960',
    supportedTerminalTypes: ['mobile'],
    priceType: 'monthly',
    priceCents: 6995,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Gerät',
    includedFeatures: ['Software inklusive'],
    technicalFeatures: ['Mobiles Kassensystem'],
    sourceReference: 'Zusatzmodule.pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_ccv_a920',
    name: 'CCV A920 inklusive Software',
    providerName: 'BestPay',
    internalProductCode: 'BP-CASH-CCV-A920',
    category: 'cash_register',
    status: 'active',
    description: 'Mobiles Kassensystem CCV A920 inklusive Software.',
    manufacturer: 'CCV',
    modelName: 'A920',
    supportedTerminalTypes: ['mobile'],
    priceType: 'monthly',
    priceCents: 6495,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Gerät',
    includedFeatures: ['Software inklusive'],
    technicalFeatures: ['Mobiles Kassensystem'],
    sourceReference: 'Zusatzmodule.pdf',
    notes:
      'Die Quelle nennt CCV A920 und CCV A77 gemeinsam zum gleichen monatlichen Preis. A77 wird als separates Produkt geführt.',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_ccv_a77',
    name: 'CCV A77 inklusive Software',
    providerName: 'BestPay',
    internalProductCode: 'BP-CASH-CCV-A77',
    category: 'cash_register',
    status: 'active',
    description: 'Mobiles Kassensystem CCV A77 inklusive Software.',
    manufacturer: 'CCV',
    modelName: 'A77',
    supportedTerminalTypes: ['mobile'],
    priceType: 'monthly',
    priceCents: 6495,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Gerät',
    includedFeatures: ['Software inklusive'],
    technicalFeatures: ['Mobiles Kassensystem'],
    sourceReference: 'Zusatzmodule.pdf',
    notes:
      'Die Quelle nennt CCV A920 und CCV A77 gemeinsam zum gleichen monatlichen Preis.',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_a920_display_logo',
    name: 'A920 Display und Logodruck',
    providerName: 'BestPay',
    internalProductCode: 'BP-A920-DISPLAY-LOGO',
    category: 'accessory',
    status: 'active',
    description: 'Individuelles Displaylogo und Logodruck für das A920.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['mobile'],
    priceType: 'one_time',
    priceCents: 14995,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Gestaltung',
    includedFeatures: [],
    technicalFeatures: [],
    sourceReference: 'Flyer BP (Marc).pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_a920_receipt_rolls_50',
    name: 'A920 Bonrollenpaket',
    providerName: 'BestPay',
    internalProductCode: 'BP-A920-RECEIPT-ROLLS-50',
    category: 'accessory',
    status: 'active',
    description: 'Paket mit 50 Bonrollen für das A920.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['mobile'],
    priceType: 'one_time',
    priceCents: 4950,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'Paket mit 50 Rollen',
    includedFeatures: [],
    technicalFeatures: ['50 Rollen', '0,99 € je Rolle'],
    sourceReference: 'Flyer BP (Marc).pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_a920_sim',
    name: 'A920 SIM-Karte',
    providerName: 'BestPay',
    internalProductCode: 'BP-A920-SIM',
    category: 'accessory',
    status: 'active',
    description: 'Optionale SIM-Karte für das A920.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['mobile'],
    priceType: 'monthly',
    priceCents: 495,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je SIM-Karte',
    includedFeatures: [],
    technicalFeatures: [],
    sourceReference: 'Flyer BP (Marc).pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_a920_case',
    name: 'A920 Terminalhülle',
    providerName: 'BestPay',
    internalProductCode: 'BP-A920-CASE',
    category: 'accessory',
    status: 'active',
    description: 'Terminalhülle für CCV A920.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['mobile'],
    priceType: 'one_time',
    priceCents: 3995,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Hülle',
    includedFeatures: [],
    technicalFeatures: ['Passend für CCV A920'],
    sourceReference: 'Flyer BP (Marc).pdf',
    notes:
      'Andere Unterlagen nennen die Hülle auch für A77 und A960. In diesem Katalog wird zunächst die belegte A920-Zuordnung verwendet.',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_a920_holder',
    name: 'A920 Terminalhalterung',
    providerName: 'BestPay',
    internalProductCode: 'BP-A920-HOLDER',
    category: 'accessory',
    status: 'active',
    description: 'Terminalhalterung für das A920.',
    manufacturer: null,
    modelName: null,
    supportedTerminalTypes: ['mobile'],
    priceType: 'one_time',
    priceCents: 8995,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Halterung',
    includedFeatures: [],
    technicalFeatures: [],
    sourceReference: 'Flyer BP (Marc).pdf',
    notes: '',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_t2',
    name: 'Speedypay T2',
    providerName: 'BestPay',
    internalProductCode: 'BP-CASH-T2',
    category: 'cash_register',
    status: 'active',
    description:
      'Stationäres Android-Kassensystem mit integriertem Belegdrucker und großem Kundenbildschirm.',
    manufacturer: null,
    modelName: 'T2',
    supportedTerminalTypes: ['stationary'],
    priceType: 'on_request',
    priceCents: null,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Kassensystem',
    includedFeatures: [],
    technicalFeatures: [
      'Stationäre Registrierkasse',
      'Integrierter Belegdrucker',
      'Großer Kundenbildschirm',
      'TSE-konform',
      'GoBD-konform',
      'KassenSichV-konform',
      'DATEV',
      'Software made in Germany',
    ],
    sourceReference: 'Blanko Angebote.pdf, Seite 1',
    notes: 'Mietmodell. Laufzeit und Preise werden im Blanko-Angebot individuell eingetragen.',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_v3',
    name: 'Speedypay V3',
    providerName: 'BestPay',
    internalProductCode: 'BP-CASH-V3',
    category: 'cash_register',
    status: 'active',
    description:
      'Stationär und mobil einsetzbares Android-Kassensystem mit integriertem Belegdrucker und Standfuß.',
    manufacturer: null,
    modelName: 'V3',
    supportedTerminalTypes: ['stationary', 'mobile'],
    priceType: 'on_request',
    priceCents: null,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Kassensystem',
    includedFeatures: [],
    technicalFeatures: [
      'Stationär und mobil einsetzbar',
      'Integrierter Belegdrucker',
      'Standfuß',
      'TSE-konform',
      'GoBD-konform',
      'KassenSichV-konform',
      'DATEV',
      'Software made in Germany',
    ],
    sourceReference: 'Blanko Angebote.pdf, Seite 2',
    notes: 'Mietmodell. Laufzeit und Preise werden im Blanko-Angebot individuell eingetragen.',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
  {
    id: 'product_speedypay_a920_cash_register',
    name: 'Speedypay A920 Kassensystem',
    providerName: 'BestPay',
    internalProductCode: 'BP-CASH-A920-REGISTER',
    category: 'cash_register',
    status: 'active',
    description:
      'Mobiles Android-Handheld-Kassensystem mit Kartenzahlung und integriertem Belegdrucker.',
    manufacturer: 'CCV',
    modelName: 'A920',
    supportedTerminalTypes: ['mobile'],
    priceType: 'on_request',
    priceCents: null,
    secondaryPriceType: null,
    secondaryPriceCents: null,
    secondaryPriceLabel: null,
    unitLabel: 'je Kassensystem',
    includedFeatures: [],
    technicalFeatures: [
      'Handheld-Kasse',
      'Kartenzahlung im selben Gerät',
      'Integrierter Belegdrucker',
      'TSE-konform',
      'GoBD-konform',
      'KassenSichV-konform',
      'DATEV',
      'Software made in Germany',
    ],
    sourceReference: 'Blanko Angebote.pdf, Seite 3',
    notes: 'Mietmodell. Laufzeit und Preise werden im Blanko-Angebot individuell eingetragen.',
    validFrom: null,
    validUntil: null,
    createdAt: '2026-07-01T08:00:00.000Z',
    updatedAt: '2026-07-01T08:00:00.000Z',
  },
] as const;

export const BESTPAY_PRODUCT_IDS = new Set<string>(
  BESTPAY_PRODUCTS_RAW.map((product) => product.id),
);
