export const BILLING_FIELD_CODES = {
  PROVIDER_NAME: 'PROVIDER_NAME',
  DOCUMENT_TITLE: 'DOCUMENT_TITLE',
  INVOICE_NUMBER: 'INVOICE_NUMBER',
  BILLING_NUMBER: 'BILLING_NUMBER',
  CUSTOMER_NUMBER: 'CUSTOMER_NUMBER',
  CONTRACT_NUMBER: 'CONTRACT_NUMBER',
  TERMINAL_NUMBER: 'TERMINAL_NUMBER',
  BILLING_DATE: 'BILLING_DATE',
  PERIOD_FROM: 'PERIOD_FROM',
  PERIOD_TO: 'PERIOD_TO',
  CURRENCY: 'CURRENCY',
  NET_GROSS_BASIS: 'NET_GROSS_BASIS',
  VAT_AMOUNT: 'VAT_AMOUNT',
  CARD_VOLUME: 'CARD_VOLUME',
  TOTAL_VOLUME: 'TOTAL_VOLUME',
  GIROCARD_VOLUME: 'GIROCARD_VOLUME',
  CREDIT_CARD_VOLUME: 'CREDIT_CARD_VOLUME',
  TRANSACTION_COUNT: 'TRANSACTION_COUNT',
  GIROCARD_TRANSACTIONS: 'GIROCARD_TRANSACTIONS',
  CREDIT_CARD_TRANSACTIONS: 'CREDIT_CARD_TRANSACTIONS',
  AVERAGE_TICKET: 'AVERAGE_TICKET',
  MONTHLY_BASE_FEE: 'MONTHLY_BASE_FEE',
  SERVICE_FEE: 'SERVICE_FEE',
  TERMINAL_RENTAL: 'TERMINAL_RENTAL',
  TERMINAL_COUNT: 'TERMINAL_COUNT',
  TRANSACTION_FEE_PER_TX: 'TRANSACTION_FEE_PER_TX',
  TRANSACTION_FEES_TOTAL: 'TRANSACTION_FEES_TOTAL',
  VOLUME_BASED_FEE_PERCENT: 'VOLUME_BASED_FEE_PERCENT',
  VOLUME_BASED_FEES_TOTAL: 'VOLUME_BASED_FEES_TOTAL',
  CLEARING_FEE: 'CLEARING_FEE',
  ONE_TIME_FEE: 'ONE_TIME_FEE',
  CREDIT_NOTE: 'CREDIT_NOTE',
  TOTAL_AMOUNT: 'TOTAL_AMOUNT',
} as const;

export type BillingFieldCode = (typeof BILLING_FIELD_CODES)[keyof typeof BILLING_FIELD_CODES];

export type BillingFieldCategory =
  | 'identification'
  | 'period'
  | 'volume'
  | 'fixed_cost'
  | 'variable_cost'
  | 'one_time'
  | 'tax'
  | 'total';

export const BILLING_FIELD_CATEGORY: Record<BillingFieldCode, BillingFieldCategory> = {
  PROVIDER_NAME: 'identification',
  DOCUMENT_TITLE: 'identification',
  INVOICE_NUMBER: 'identification',
  BILLING_NUMBER: 'identification',
  CUSTOMER_NUMBER: 'identification',
  CONTRACT_NUMBER: 'identification',
  TERMINAL_NUMBER: 'identification',
  BILLING_DATE: 'period',
  PERIOD_FROM: 'period',
  PERIOD_TO: 'period',
  CURRENCY: 'identification',
  NET_GROSS_BASIS: 'identification',
  VAT_AMOUNT: 'tax',
  CARD_VOLUME: 'volume',
  TOTAL_VOLUME: 'volume',
  GIROCARD_VOLUME: 'volume',
  CREDIT_CARD_VOLUME: 'volume',
  TRANSACTION_COUNT: 'volume',
  GIROCARD_TRANSACTIONS: 'volume',
  CREDIT_CARD_TRANSACTIONS: 'volume',
  AVERAGE_TICKET: 'volume',
  MONTHLY_BASE_FEE: 'fixed_cost',
  SERVICE_FEE: 'fixed_cost',
  TERMINAL_RENTAL: 'fixed_cost',
  TERMINAL_COUNT: 'fixed_cost',
  TRANSACTION_FEE_PER_TX: 'variable_cost',
  TRANSACTION_FEES_TOTAL: 'variable_cost',
  VOLUME_BASED_FEE_PERCENT: 'variable_cost',
  VOLUME_BASED_FEES_TOTAL: 'variable_cost',
  CLEARING_FEE: 'variable_cost',
  ONE_TIME_FEE: 'one_time',
  CREDIT_NOTE: 'one_time',
  TOTAL_AMOUNT: 'total',
};
