export type BillingFindingSeverity = 'info' | 'warning' | 'error' | 'blocking';

export type BillingFindingCategory =
  | 'file'
  | 'extraction'
  | 'document'
  | 'period'
  | 'currency'
  | 'field'
  | 'cost'
  | 'duplicate'
  | 'correction'
  | 'outlier'
  | 'quality'
  | 'lifecycle'
  | 'permission'
  | 'storage';

export const BILLING_FINDING_CODES = {
  BILLING_FILE_TYPE_UNSUPPORTED: 'BILLING_FILE_TYPE_UNSUPPORTED',
  BILLING_FILE_TOO_LARGE: 'BILLING_FILE_TOO_LARGE',
  BILLING_FILE_EMPTY: 'BILLING_FILE_EMPTY',
  BILLING_FILE_CORRUPTED: 'BILLING_FILE_CORRUPTED',
  BILLING_PDF_PASSWORD_PROTECTED: 'BILLING_PDF_PASSWORD_PROTECTED',
  BILLING_OCR_UNAVAILABLE: 'BILLING_OCR_UNAVAILABLE',
  BILLING_OCR_FAILED: 'BILLING_OCR_FAILED',
  BILLING_TEXT_EXTRACTION_FAILED: 'BILLING_TEXT_EXTRACTION_FAILED',
  BILLING_DOCUMENT_UNREADABLE: 'BILLING_DOCUMENT_UNREADABLE',
  BILLING_DOCUMENT_DUPLICATE: 'BILLING_DOCUMENT_DUPLICATE',
  BILLING_DOCUMENT_POSSIBLE_DUPLICATE: 'BILLING_DOCUMENT_POSSIBLE_DUPLICATE',
  BILLING_DOCUMENT_TYPE_UNKNOWN: 'BILLING_DOCUMENT_TYPE_UNKNOWN',
  BILLING_PERIOD_MISSING: 'BILLING_PERIOD_MISSING',
  BILLING_PERIOD_AMBIGUOUS: 'BILLING_PERIOD_AMBIGUOUS',
  BILLING_PERIOD_OVERLAP: 'BILLING_PERIOD_OVERLAP',
  BILLING_PARTIAL_PERIOD: 'BILLING_PARTIAL_PERIOD',
  BILLING_MULTI_MONTH_PERIOD: 'BILLING_MULTI_MONTH_PERIOD',
  BILLING_CURRENCY_MISSING: 'BILLING_CURRENCY_MISSING',
  BILLING_CURRENCY_CONFLICT: 'BILLING_CURRENCY_CONFLICT',
  BILLING_NET_GROSS_AMBIGUOUS: 'BILLING_NET_GROSS_AMBIGUOUS',
  BILLING_FIELD_LOW_CONFIDENCE: 'BILLING_FIELD_LOW_CONFIDENCE',
  BILLING_FIELD_AMBIGUOUS: 'BILLING_FIELD_AMBIGUOUS',
  BILLING_FIELD_UNIT_MISSING: 'BILLING_FIELD_UNIT_MISSING',
  BILLING_FIELD_CONFLICT: 'BILLING_FIELD_CONFLICT',
  BILLING_TOTAL_MISMATCH: 'BILLING_TOTAL_MISMATCH',
  BILLING_TRANSACTION_COUNT_MISSING: 'BILLING_TRANSACTION_COUNT_MISSING',
  BILLING_CARD_VOLUME_MISSING: 'BILLING_CARD_VOLUME_MISSING',
  BILLING_ONE_TIME_COST_DETECTED: 'BILLING_ONE_TIME_COST_DETECTED',
  BILLING_CREDIT_NOTE_DETECTED: 'BILLING_CREDIT_NOTE_DETECTED',
  BILLING_CORRECTION_UNRESOLVED: 'BILLING_CORRECTION_UNRESOLVED',
  BILLING_OUTLIER_DETECTED: 'BILLING_OUTLIER_DETECTED',
  BILLING_BASELINE_INCOMPLETE: 'BILLING_BASELINE_INCOMPLETE',
  BILLING_BASELINE_NOT_COMPARABLE: 'BILLING_BASELINE_NOT_COMPARABLE',
  BILLING_CONFIRMATION_REQUIRED: 'BILLING_CONFIRMATION_REQUIRED',
  BILLING_STALE: 'BILLING_STALE',
  BILLING_ORIGINAL_DOCUMENT_NOT_PERSISTED: 'BILLING_ORIGINAL_DOCUMENT_NOT_PERSISTED',
  BILLING_OCR_WORKER_LOAD_FAILED: 'BILLING_OCR_WORKER_LOAD_FAILED',
  BILLING_OCR_LANGUAGE_LOAD_FAILED: 'BILLING_OCR_LANGUAGE_LOAD_FAILED',
  BILLING_OCR_ABORTED: 'BILLING_OCR_ABORTED',
  BILLING_OCR_TIMEOUT: 'BILLING_OCR_TIMEOUT',
  BILLING_OCR_NO_TEXT: 'BILLING_OCR_NO_TEXT',
  BILLING_OCR_LOW_QUALITY: 'BILLING_OCR_LOW_QUALITY',
  BILLING_IMAGE_DECODE_FAILED: 'BILLING_IMAGE_DECODE_FAILED',
  BILLING_IMAGE_TOO_SMALL: 'BILLING_IMAGE_TOO_SMALL',
  BILLING_IMAGE_PREPROCESSING_FAILED: 'BILLING_IMAGE_PREPROCESSING_FAILED',
  BILLING_PDF_PAGE_RENDER_FAILED: 'BILLING_PDF_PAGE_RENDER_FAILED',
} as const;

export type BillingFindingCode =
  (typeof BILLING_FINDING_CODES)[keyof typeof BILLING_FINDING_CODES];

export interface BillingImportFinding {
  code: BillingFindingCode;
  severity: BillingFindingSeverity;
  category: BillingFindingCategory;
  documentId: string | null;
  fieldId: string | null;
  blocking: boolean;
  internalDescription: string;
  salesDescription: string | null;
  requiredAction: string | null;
  context: Record<string, string | number | boolean | null>;
}

export function createBillingFinding(
  partial: Omit<BillingImportFinding, 'context'> & {
    context?: BillingImportFinding['context'];
  },
): BillingImportFinding {
  return { ...partial, context: partial.context ?? {} };
}
